#!/bin/bash

SCHEME="Unity-iPhone"
PROJECT_PATH="${PROJECT_DIR}/${SCHEME}.xcodeproj"
ARCHIVE_FILE="${SCHEME}.xcarchive"
ARCHIVE_DIR="${PROJECT_DIR}/archive"
ARCHIVE_PATH="${ARCHIVE_DIR}/${ARCHIVE_FILE}"
IPA_OUTPUT_DIR="output_ipa"
IPA_PATH="${ARCHIVE_DIR}/${IPA_OUTPUT_DIR}"
EXPORT_OPTIONS_PLIST="ExportOptions.plist"
PROVISIONING_PROFILE="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"

mkdir -p $ARCHIVE_PATH

# ARCHIVE
xcodebuild -project $PROJECT_PATH \
    -scheme $SCHEME \
    archive -archivePath $ARCHIVE_PATH \
    PROVISIONING_PROFILE=$PROVISIONING_PROFILE

# ipaファイrの作成
xcodebuild -exportArchive -archivePath $ARCHIVE_PATH \
 -exportPath $IPA_PATH \
 -exportOptionsPlist $EXPORT_OPTIONS_PLIST \
 PROVISIONING_PROFILE=$PROVISIONING_PROFILE
